Repository openshift/restic, pull requests merged in 2023-10, with the labels that each got.

#24 CVE-2023-44487 bump x/net to 0.17.0
  go.mod
  go.sum
Labels: lgtm

#30 [oadp-1.0] upgrade x/net to 0.17.0
  go.mod
  go.sum
Labels: approved, lgtm

#31 [konveyor-0.12.1] upgrade x/net to 0.17.0
  go.mod
  go.sum
Labels: approved, lgtm

#28 [oadp-1.1] upgrade x/net to 0.17.0
  go.mod
  go.sum
  internal/restorer/restorer_test.go
  internal/restorer/restorer_unix_test.go
Labels: lgtm

#27 [konveyor-0.15.0] upgrade x/net to 0.17.0
  go.mod
  go.sum
Labels: lgtm

#29 [konveyor-0.14.0] upgrade x/net to 0.17.0`
  go.mod
  go.sum
  internal/restorer/restorer_test.go
  internal/restorer/restorer_unix_test.go
Labels: approved

#34 fix unit tests for MTC changes
  internal/backend/rest/rest_int_go114_test.go
  internal/restic/snapshot_policy_test.go
  internal/restorer/restorer_test.go
  internal/restorer/restorer_unix_test.go
Labels: approved, lgtm

#32 fix: upgrade Go version
  go.mod
Labels: lgtm, do-not-merge/hold

#33 [oadp-1.2] update go.mod to 1.19
  go.mod
Labels: lgtm
